### ISSUE TITLE
Running this on windows

### ISSUE THREAD

**Issue by Overdrivr** [miked63017/dinolite_uvc_led_control#1]
Hello, I just stumbled upon this very young repo, do think this could run on Windows (with quite a lot of modifications I'm guessing) ? 

For instance I saw that you're using the `uvcdynctrl` package, does it mean that those microscopes are running with pretty standard USB protocol like Video class device ?

Cheers

**Comment by miked63017** [comment]
Its possible it could work, you would have to install uvcdynctrl and have it in your $PATH environment at the minimum. For one of the models I am working with a kernel patch is required in linux, I am not sure where, how, or if that would need to be handled on windows honestly. Give it a try and see if it works, I don't run windows anywhere so I cannot test. If it does work, or mostly works but needs a few tweaks I am open to Pull Requests just let me know.

**Comment by SolesenOfDunwell** [comment]
Modern Dino-Lite microscopes (any with 4 numerical digits in the model number) use the UVC driver.

For Windows development there is a free SDK for Dino-Lite. Simply sign and submit the agreement to support@dinolite.us which you can find here:
http://www.dinolite.us/dl/dino-sdk.pdf

**Comment by Overdrivr** [comment]
@SolesenOfDunwell thanks a lot for the info ! Do you know if the SDK offers a python implementation/wrapper ?

**Comment by Overdrivr** [comment]
And thanks @miked63017 for your feedback

**Comment by SolesenOfDunwell** [comment]
My pleasure @Overdrivr. I don't believe so, but you can see the list of supported environments and more information here:
https://www.dinolite.us/about-the-dino-lite-sdk
