### ISSUE TITLE
Any information on which models need the kernel patch?

### ISSUE THREAD

**Issue by ohle** [miked63017/dinolite_uvc_led_control#2]
The readme says

> Please look in kernelpatch.diff to see the details, it is a small one but you will need to rebuild the kernel and boot into the newly built kernel for this to work with the older Dino Lite models

Do you have any information what constitutes an "older" model? Is there anything I can see in their spec sheets to decide wether I'm going to need a patched kernel to contol the LEDs?

**Comment by shaun-ba** [comment]
@ohle  did you have any luck getting this to work?

I've added my model to "dinoliteuvccontrol.py" but i'm just getting this trace:

```
File "/usr/local/lib/python2.7/dist-packages/dinoliteuvccontrol-0.0.1-py2.7.egg/dinoliteuvccontrol/dinoliteuvccontrol.py", line 37, in __init__
    from devices import device0960
```

**Comment by shaun-ba** [comment]
Scrap the above you have to add a module in /devices/ !

**Comment by miked63017** [comment]
Sorry for the late response, I honestly haven't gotten any notifications on this repo. It is possible that your device may work using one of the existing modules even if the deviceid doesn't match, but you will need to hack around a little to tell this module to allow it to be used. If it doesn't work then yes, you will definitely need to add your own module to this one with whatever information is specific to your model. Unfortunately I do not own a bunch of models so I couldn't make and/or test each one. 

If you look in https://github.com/miked63017/dinolite_uvc_led_control/blob/master/dinoliteuvccontrol/dinoliteuvccontrol.py you could try adding your id in to the if statement and allow it to load one of the existing modules to test compatibility. I am not really working on this project anymore so if you find that other devices work for these modules feel free to put in a PR and I will merge.
